title: Neutron Imaging e-Learning
sidebar: toc
authors:
  anders:
    name: Anders Kaestner
    display_name: Anders
    gravatar: c66919cb194f96c696c1da0c47354a6a
    email: anders.kaestner@psi.ch
    web: http://www.psi.ch
    github: anderskaestner
description: "In this blog I am posting the progress of my e-learning notebooks."
future: false

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
